const QUERY_KEYS = {
  CURRENT_USER: "CURRENT_USER",
  QUIZZES: "QUIZZES",
  CURRENT_ROOM: "CURRENT_ROOM",
  PAST_ROOMS:"PAST_ROOMS",
  QUIZ_QUESTIONS: "QUIZ_QUESTIONS",
};

export default QUERY_KEYS;